# forecast configuration

n_en: 20  # number of ensembles
start: '2000-01-01'
stop: '2010-01-01'

#  see 4_pb_model/notes/model_variable_description.txt for output variable details
sntemp_output: ['seg_rain', 'seg_tave_air', 'seg_tave_water', 'seg_outflow', 'seg_tave_gw',
'seg_tave_sroff', 'seg_tave_ss', 'seg_tave_upstream', 'seg_upstream_inflow', 'seginc_gwflow',
'seginc_potet', 'seginc_sroff', 'seginc_ssflow', 'seginc_swrad', 'seg_humid', 'seg_shade', 'seg_ccov', 'seg_width']


orig_model_loc: 'prms_sntemp/20191002_Delaware_streamtemp'

pb_model_run_loc: '4_pb_model/tmp'

